version: '3.7'

services:
  fiapshop-mspedidos:
    image: mongodb/mongodb-community-server:latest
    container_name: fiapshop-mspedidos
    environment:
      MONGO_INITDB_DATABASE: fiapshop1
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db